version: "3.7"
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql_${MYSQL_VERSION}
    ports:
      - ${REAL_MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_DIR}/data:/var/lib/mysql
      - ${MYSQL_DIR}/my.cnf:/etc/mysql/my.cnf
      - ${MYSQL_DIR}/logs:/logs
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    # restart: always
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis_${REDIS_VERSION}
    ports:
      - ${REAL_REDIS_PORT}:6379
    volumes:
      - ${REDIS_DIR}/data:/data
      - ${REDIS_DIR}/redis.conf:/etc/redis/redis.conf
      - ${REDIS_DIR}/logs:/logs
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    # restart: always
    command: [ "redis-server", "/etc/redis/redis.conf" ]
  mongo:
    image: mongo:${MONGO_VERSION}
    container_name: mongo_${MONGO_VERSION}
    ports:
      - ${REAL_MONGO_PORT}:27017
    volumes:
     - ${MONGO_DIR}/db:/data/db # 挂载数据目录
     - ${MONGO_DIR}/log:/var/log/mongodb  # 挂载日志目录
     - ${MONGO_DIR}/config:/etc/mongo  # 挂载配置目录
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
